import type { Metadata } from "next";
import Header from "./_components/Header";
import "./globals.css";

import { Space_Grotesk, Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "./_components/Footer";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"], variable: "--font-space-grotesk" });

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={cn(fontSans.variable, spaceGrotesk.className)}>
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
